services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FriendsOfTYPO3\Kickstarter\:
    resource: '../Classes/*'

  FriendsOfTYPO3\Kickstarter\Configuration\ExtConf:
    public: true

  ##############
  ## COMMANDS ##
  ##############

  FriendsOfTYPO3\Kickstarter\Command\ApplyTypo3CglCommand:
    arguments:
      $questionCollection: '@questions.apply-typo3-cgl'

  FriendsOfTYPO3\Kickstarter\Command\CommandCommand:
    arguments:
      $questionCollection: '@questions.command'

  FriendsOfTYPO3\Kickstarter\Command\ControllerCommand:
    arguments:
      $questionCollection: '@questions.controller'

  FriendsOfTYPO3\Kickstarter\Command\EventCommand:
    arguments:
      $questionCollection: '@questions.event'

  FriendsOfTYPO3\Kickstarter\Command\EventListenerCommand:
    arguments:
      $questionCollection: '@questions.event-listener'

  FriendsOfTYPO3\Kickstarter\Command\ExtensionCommand:
    arguments:
      $questionCollection: '@questions.extension'

  FriendsOfTYPO3\Kickstarter\Command\LocallangCommand:
    arguments:
      $questionCollection: '@questions.locallang'

  FriendsOfTYPO3\Kickstarter\Command\MiddlewareCommand:
    arguments:
      $questionCollection: '@questions.middleware'

  FriendsOfTYPO3\Kickstarter\Command\ModelCommand:
    arguments:
      $questionCollection: '@questions.model'

  FriendsOfTYPO3\Kickstarter\Command\ModuleCommand:
    arguments:
      $questionCollection: '@questions.module'

  FriendsOfTYPO3\Kickstarter\Command\PluginCommand:
    arguments:
      $questionCollection: '@questions.plugin'

  FriendsOfTYPO3\Kickstarter\Command\RepositoryCommand:
    arguments:
      $questionCollection: '@questions.repository'

  FriendsOfTYPO3\Kickstarter\Command\ServicesYamlCommand:
    arguments:
      $questionCollection: '@questions.services-yaml'

  FriendsOfTYPO3\Kickstarter\Command\SitePackageCommand:
    arguments:
      $questionCollection: '@questions.site-package'

  FriendsOfTYPO3\Kickstarter\Command\SiteSetCommand:
    arguments:
      $questionCollection: '@questions.site-set'

  FriendsOfTYPO3\Kickstarter\Command\SiteSettingsDefinitionCommand:
    arguments:
      $questionCollection: '@questions.site-settings-definition'

  FriendsOfTYPO3\Kickstarter\Command\TableCommand:
    arguments:
      $questionCollection: '@questions.table'

  FriendsOfTYPO3\Kickstarter\Command\TestEnvCommand:
    arguments:
      $questionCollection: '@questions.test-env'

  FriendsOfTYPO3\Kickstarter\Command\TypeConverterCommand:
    arguments:
      $questionCollection: '@questions.type-converter'

  FriendsOfTYPO3\Kickstarter\Command\UpgradeWizardCommand:
    arguments:
      $questionCollection: '@questions.upgrade-wizard'

  FriendsOfTYPO3\Kickstarter\Command\ValidatorCommand:
    arguments:
      $questionCollection: '@questions.validator'

  ######################
  ## CREATOR SERVICES ##
  ######################

  FriendsOfTYPO3\Kickstarter\Service\Creator\CommandCreatorService:
    arguments:
      $commandCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.command' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\ControllerCreatorService:
    arguments:
      $extbaseControllerCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.controller.extbase' }
      $nativeControllerCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.controller.native' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\MiddlewareCreatorService:
    arguments:
      $middlewareCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.middleware' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\ModelCreatorService:
    arguments:
      $modelCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.domain.model' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\RepositoryCreatorService:
    arguments:
      $repositoryCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.domain.repository' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\ValidatorCreatorService:
    arguments:
      $validatorCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.domain.validator' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\EventCreatorService:
    arguments:
      $eventCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.event' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\EventListenerCreatorService:
    arguments:
      $eventListenerCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.event-listener' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\ExtensionCreatorService:
    arguments:
      $extensionCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.extension' }
      $servicesConfigCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.servicesConfig' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\LocallangCreatorService:
    arguments:
      $locallangCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.locallang' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\PluginCreatorService:
    arguments:
      $extbasePluginCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.plugin.extbase' }
      $nativePluginCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.plugin.native' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\ModuleCreatorService:
    arguments:
      $extbaseModuleCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.module.extbase' }
      $nativeModuleCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.module.native' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\TypeConverterCreatorService:
    arguments:
      $typeConverterCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.property.type-converter' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\SitePackageCreatorService:
    arguments:
      $sitePackageCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.property.site-package' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\ServicesConfigCreatorService:
    arguments:
      $servicesConfigCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.servicesConfig' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\SiteSetCreatorService:
    arguments:
      $siteSetCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.site-set' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\SiteSettingsDefinitionCreatorService:
    arguments:
      $siteSettingDefinitionCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.site-settings-definition' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\TableCreatorService:
    arguments:
      $tableCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.tca.table' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\TestEnvCreatorService:
    arguments:
      $testEnvCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.test.env' }
  FriendsOfTYPO3\Kickstarter\Service\Creator\UpgradeWizardCreatorService:
    arguments:
      $upgradeCreators: !tagged_iterator { tag: 'ext-kickstarter.creator.upgrade-wizard' }

  ###############
  ## QUESTIONS ##
  ###############

  factory.question:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionFactory

  questions.apply-typo3-cgl:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.apply-typo3-cgl' }

  questions.command:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.command' }

  questions.controller:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.controller' }

  questions.event:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.event' }

  questions.event-listener:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.event-listener' }

  questions.extension:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.extension' }

  questions.locallang:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.locallang' }

  questions.middleware:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.middleware' }

  questions.model:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.model' }

  questions.module:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.module' }

  questions.plugin:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.plugin' }

  questions.repository:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.repository' }

  questions.services-yaml:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.services-yaml' }

  questions.site-package:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.site-package' }

  questions.site-set:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.site-set' }

  questions.site-settings-definition:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.site-settings-definition' }

  questions.table:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.table' }

  questions.test-env:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.test-env' }

  questions.type-converter:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.type-converter' }

  questions.upgrade-wizard:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.upgrade-wizard' }

  questions.validator:
    class: FriendsOfTYPO3\Kickstarter\Command\Input\QuestionCollection
    arguments:
      $questions: !tagged_iterator { tag: 'ext-kickstarter.command.question.validator' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Command\CommandAliasQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.command-name' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Command\CommandClassNameQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.command-class' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Command\CommandNameQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.command-name' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Controller\ActionMethodNameQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.controller-action' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Controller\ControllerClassNameQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.controller-class' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Extension\ComposerNameQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.composer_name' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Extension\EmailQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.email' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Extension\ExtensionKeyQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.extension_key' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Extension\NamespaceQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.namespace' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Extension\VersionQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.version' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Event\EventClassNameQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.event-class' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\EventListener\EventListenerClassNameQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.event-listener-class-name' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Locallang\LocallangFileNameQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.locallang_file_name' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Locallang\LocallangTransUnitIdQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.locallang_trans_unit_id' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Middleware\MiddlewareClassNameQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.middleware-class' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Middleware\MiddlewareIdentifierQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.middleware-identifier' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Model\ModelClassNameQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.model-class' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Module\ModuleIdentifierQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.module-identifier' }

  FriendsOfTYPO3\Kickstarter\Command\Input\Question\Plugin\PluginNameQuestion:
    arguments:
      $inputHandlers: !tagged_iterator { tag: 'ext-kickstarter.inputHandler.plugin-name' }
